### ISSUE TITLE
Cannot add port mappings for any internal IPs other than localhost

### ISSUE THREAD

**Issue by Roshi617** [kaklakariada/portmapper#126] opened 2024-01-09 17:52 UTC
Hello

I have been having this issues for a few days now. It happened all of a sudden. I need to forward some ports to my PS3's internal IP. I do so and it says "successfully added" however the list showing my mappings doesn't show the mapping it supposedly added. If I forward to localhost it works just fine. But not if I specify an internal client IP. I have tried all 3 libraries. Cling doesn't find my router, and weupnp and SBBI have this issue.

Upnp is functioning fine on my router; other devices are able to open ports automatically. Such as my other game consoles and softwares.

INFO  Router info:
INFO  - device type = urn:schemas-upnp-org:device:WANConnectionDevice:1
INFO  - device type cif = urn:schemas-upnp-org:device:WANDevice:1
INFO  - friendly name = RT-AC87U
INFO  - location = http://192.168.1.1:34906/rootDesc.xml
INFO  - manufacturer = ASUSTeK Computer Inc.
INFO  - model description = ASUS Wireless Router

A log of connecting to my router, it grabbing my mappings (11 of them) and then adding one mapping and it not actually adding it:

TRACE Connecting to router...
INFO  Creating router factory for class org.chris.portmapper.router.weupnp.WeUPnPRouterFactory
DEBUG Router factory weupnp lib created
INFO  Searching for routers...
DEBUG System property 'portmapper.locationUrl' not defined: discover routers automatically.
DEBUG Searching for gateway devices...
INFO  Connected to router 'RT-AC87U'
TRACE Updating addresses...
TRACE Updating port mappings...
DEBUG Connection state changed to true
DEBUG Getting port mapping 0...
DEBUG Got port mapping 0: org.bitlet.weupnp.PortMappingEntry@3a80fc3b
DEBUG Getting port mapping 1...
DEBUG Got port mapping 1: org.bitlet.weupnp.PortMappingEntry@1eeaac34
DEBUG Getting port mapping 2...
DEBUG Got port mapping 2: org.bitlet.weupnp.PortMappingEntry@4f69140f
DEBUG Getting port mapping 3...
DEBUG Got port mapping 3: org.bitlet.weupnp.PortMappingEntry@628b73bc
DEBUG Getting port mapping 4...
DEBUG Got port mapping 4: org.bitlet.weupnp.PortMappingEntry@4910b4fc
DEBUG Getting port mapping 5...
DEBUG Got port mapping 5: org.bitlet.weupnp.PortMappingEntry@f786e1d
DEBUG Getting port mapping 6...
DEBUG Got port mapping 6: org.bitlet.weupnp.PortMappingEntry@5bb840b
DEBUG Getting port mapping 7...
DEBUG Got port mapping 7: org.bitlet.weupnp.PortMappingEntry@2b730ee3
DEBUG Getting port mapping 8...
DEBUG Got port mapping 8: org.bitlet.weupnp.PortMappingEntry@7ceb4b8d
DEBUG Getting port mapping 9...
DEBUG Got port mapping 9: org.bitlet.weupnp.PortMappingEntry@4a497e5f
DEBUG Getting port mapping 10...
DEBUG Got port mapping 10: org.bitlet.weupnp.PortMappingEntry@30f85d6f
DEBUG Getting port mapping 11...
DEBUG Got port mapping 11: org.bitlet.weupnp.PortMappingEntry@6b8b31b8
DEBUG Getting port mapping 12...
DEBUG Entry 12 does not exist, stop getting more mappings
DEBUG Got null port mapping for index 12
INFO  Found 12 mappings
TRACE done
TRACE Selection of preset list has changed: true
TRACE Selection of preset list has changed: true
DEBUG Connected to router, get IP of localhost from socket...
DEBUG Get IP of localhost
DEBUG Got internal router port 34906
DEBUG Creating socket to router: 192.168.1.1:34906...
DEBUG Got address /192.168.1.92 from socket.
INFO  1 port mapping added successfully
DEBUG Getting port mapping 0...
DEBUG Got port mapping 0: org.bitlet.weupnp.PortMappingEntry@60e6f3bd
DEBUG Getting port mapping 1...
DEBUG Got port mapping 1: org.bitlet.weupnp.PortMappingEntry@684fd8f3
DEBUG Getting port mapping 2...
DEBUG Got port mapping 2: org.bitlet.weupnp.PortMappingEntry@5470fdb8
DEBUG Getting port mapping 3...
DEBUG Got port mapping 3: org.bitlet.weupnp.PortMappingEntry@5c6507c8
DEBUG Getting port mapping 4...
DEBUG Got port mapping 4: org.bitlet.weupnp.PortMappingEntry@84bed90
DEBUG Getting port mapping 5...
DEBUG Got port mapping 5: org.bitlet.weupnp.PortMappingEntry@50ecb1af
DEBUG Getting port mapping 6...
DEBUG Got port mapping 6: org.bitlet.weupnp.PortMappingEntry@42101fba
DEBUG Getting port mapping 7...
DEBUG Got port mapping 7: org.bitlet.weupnp.PortMappingEntry@f8950a1
DEBUG Getting port mapping 8...
DEBUG Got port mapping 8: org.bitlet.weupnp.PortMappingEntry@313c5b63
DEBUG Getting port mapping 9...
DEBUG Got port mapping 9: org.bitlet.weupnp.PortMappingEntry@4b0e0f55
DEBUG Getting port mapping 10...
DEBUG Got port mapping 10: org.bitlet.weupnp.PortMappingEntry@3091a88d
DEBUG Getting port mapping 11...
DEBUG Got port mapping 11: org.bitlet.weupnp.PortMappingEntry@2338822c
DEBUG Getting port mapping 12...
DEBUG Entry 12 does not exist, stop getting more mappings
DEBUG Got null port mapping for index 12
INFO  Found 12 mappings

I need some help here. This used to work but the other day it suddenly started behaving this way.

**Comment by kaklakariada** [comment] 2024-02-03 07:33
Hi @Roshi617 ,

the problem you describe could be caused by changes in your router. It's possible that it automatically installed a new firmware and the new firmware allows port forwardings only for localhost. Please check if it's possible to change this in your router's settings.

**Comment by kaklakariada** [comment] 2024-08-04 07:11
I am closing this. If the problem still exists feel free to re-open this issue.

**Closed by kaklakariada** 2024-08-04 07:11 UTC
Labels: question
